/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomEndpointInput: typeof import('./src/components/CustomEndpointInput.vue')['default']
    EndpointError: typeof import('./src/components/EndpointError.vue')['default']
    EndpointRow: typeof import('./src/components/EndpointRow.vue')['default']
    NetworkStatusRow: typeof import('./src/components/NetworkStatusRow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableHeader: typeof import('./src/components/TableHeader.vue')['default']
  }
}
